<?php

use Illuminate\Database\Seeder;

class AttachmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attachments')->delete();
        
        \DB::table('attachments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'attachable_id' => NULL,
                'attachable_type' => NULL,
                'attachmenttype_id' => NULL,
                'path' => 'uploads/2018/09/k6yVdCKzKyg8mvVqg3JY2HgSv0wmIXNqVvkhW7eR.pdf',
                'description' => 'Security check',
                'filename' => NULL,
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'created_at' => '2018-09-26 14:39:16',
                'updated_at' => '2018-09-26 14:39:16',
            ),
            1 => 
            array (
                'id' => 2,
                'attachable_id' => NULL,
                'attachable_type' => NULL,
                'attachmenttype_id' => NULL,
                'path' => 'uploads/2018/09/ffJJRZKtEdjaczzgjb74oG2xogGAsxk89rJPbucB.pdf',
                'description' => 'Security check',
                'filename' => NULL,
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'created_at' => '2018-09-26 14:39:24',
                'updated_at' => '2018-09-26 14:39:24',
            ),
            2 => 
            array (
                'id' => 3,
                'attachable_id' => NULL,
                'attachable_type' => NULL,
                'attachmenttype_id' => NULL,
                'path' => 'uploads/2018/09/nArOnwwmUczrBLJAFp2TIYuXe0ftziP9rg27Cq2A.pdf',
                'description' => 'Security check',
                'filename' => NULL,
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'created_at' => '2018-09-26 14:39:40',
                'updated_at' => '2018-09-26 14:39:40',
            ),
            3 => 
            array (
                'id' => 4,
                'attachable_id' => 1,
                'attachable_type' => 'company',
                'attachmenttype_id' => 5,
                'path' => 'uploads/2018/09/9BrsElvGXbiKyvoW4PwzM842tQIKSup1UzUm2sRB.pdf',
                'description' => 'Trade license',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'created_at' => '2018-09-26 14:40:53',
                'updated_at' => '2018-09-26 14:40:53',
            ),
            4 => 
            array (
                'id' => 5,
                'attachable_id' => 1,
                'attachable_type' => 'company',
                'attachmenttype_id' => 20,
                'path' => 'uploads/2018/09/UaZV6jRCYG9ZultGS3YI5Sk5guI1oqtUnASQsSPV.pdf',
                'description' => 'Tax Certificate',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'created_at' => '2018-09-26 14:40:56',
                'updated_at' => '2018-09-26 14:40:56',
            ),
            5 => 
            array (
                'id' => 6,
                'attachable_id' => 1,
                'attachable_type' => 'company',
                'attachmenttype_id' => 9,
                'path' => 'uploads/2018/09/hzh2E8wB7204alMwi1puDWha4vNuOq83wQkvIOJF.pdf',
                'description' => 'Articles of association',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'created_at' => '2018-09-26 14:40:59',
                'updated_at' => '2018-09-26 14:40:59',
            ),
            6 => 
            array (
                'id' => 7,
                'attachable_id' => 1,
                'attachable_type' => 'companyowner',
                'attachmenttype_id' => 1,
                'path' => 'uploads/2018/09/oKAjakmjs0HRXmwBLjcavT2fYftanDH6h35IX8pB.pdf',
                'description' => 'Owner ID 5b83e44e955acsi-2.pdf',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'created_at' => '2018-09-26 14:41:16',
                'updated_at' => '2018-09-26 14:41:16',
            ),
            7 => 
            array (
                'id' => 8,
                'attachable_id' => 1,
                'attachable_type' => 'companydirector',
                'attachmenttype_id' => 3,
                'path' => 'uploads/2018/09/TaJexBEbE0iUVG7stxdAMDDg5K59limUftGWMD3g.pdf',
                'description' => 'Director ID 5b83e44e955acsi-2.pdf',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 7,
                'updated_by' => 7,
                'created_at' => '2018-09-26 14:41:54',
                'updated_at' => '2018-09-26 14:41:54',
            ),
            8 => 
            array (
                'id' => 9,
                'attachable_id' => 2,
                'attachable_type' => 'company',
                'attachmenttype_id' => 5,
                'path' => 'uploads/2018/09/CXcnCAYEXthlvAOCeV2XZPfASzNlEWxRsovVVmMI.pdf',
                'description' => 'Trade license',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2018-09-26 14:48:58',
                'updated_at' => '2018-09-26 14:48:58',
            ),
            9 => 
            array (
                'id' => 10,
                'attachable_id' => NULL,
                'attachable_type' => NULL,
                'attachmenttype_id' => NULL,
                'path' => 'uploads/2018/09/YswlfSa8eq15k5AdjnyYNDXP02O3DQLDbvEIOW9w.pdf',
                'description' => 'Security check',
                'filename' => NULL,
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2018-09-26 14:49:01',
                'updated_at' => '2018-09-26 14:49:01',
            ),
            10 => 
            array (
                'id' => 11,
                'attachable_id' => 2,
                'attachable_type' => 'company',
                'attachmenttype_id' => 20,
                'path' => 'uploads/2018/09/4iGjR8UJOlLxESt9nBfTyEY27L4w9jclZ2N7PCEo.pdf',
                'description' => 'Tax Certificate',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2018-09-26 14:49:05',
                'updated_at' => '2018-09-26 14:49:05',
            ),
            11 => 
            array (
                'id' => 12,
                'attachable_id' => 2,
                'attachable_type' => 'company',
                'attachmenttype_id' => 9,
                'path' => 'uploads/2018/09/sfgEb9VCYBqJS23TOVimP4EUW4fTFy9h4QTznKSQ.pdf',
                'description' => 'Articles of association',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2018-09-26 14:49:16',
                'updated_at' => '2018-09-26 14:49:16',
            ),
            12 => 
            array (
                'id' => 13,
                'attachable_id' => 2,
                'attachable_type' => 'companyowner',
                'attachmenttype_id' => 1,
                'path' => 'uploads/2018/09/H7QrH8TKTBmjRnjwlEBaeFwrbAv7eQnlSNc6E5Jf.pdf',
                'description' => 'Owner ID 5b83e44e955acsi-2.pdf',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2018-09-26 14:49:38',
                'updated_at' => '2018-09-26 14:49:38',
            ),
            13 => 
            array (
                'id' => 14,
                'attachable_id' => 2,
                'attachable_type' => 'companydirector',
                'attachmenttype_id' => 3,
                'path' => 'uploads/2018/09/wyIDy8du2D715UZcoKe3DgxCoP0dlP9jSWr5Uzcc.pdf',
                'description' => 'Director ID 5b83e44e955acsi-2.pdf',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2018-09-26 14:49:58',
                'updated_at' => '2018-09-26 14:49:58',
            ),
            14 => 
            array (
                'id' => 15,
                'attachable_id' => 3,
                'attachable_type' => 'company',
                'attachmenttype_id' => 5,
                'path' => 'uploads/2018/09/XAvgGuVX4DLaJ9HN9OtkpqmtyX3pL8BIwuHBbURJ.pdf',
                'description' => 'Trade license',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 9,
                'updated_by' => 9,
                'created_at' => '2018-09-26 14:53:36',
                'updated_at' => '2018-09-26 14:53:36',
            ),
            15 => 
            array (
                'id' => 16,
                'attachable_id' => 3,
                'attachable_type' => 'company',
                'attachmenttype_id' => 20,
                'path' => 'uploads/2018/09/7b1IP7Uix04xQqiRGTZceyveO7CNw8SL4DncgRpt.pdf',
                'description' => 'Tax Certificate',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 9,
                'updated_by' => 9,
                'created_at' => '2018-09-26 14:53:38',
                'updated_at' => '2018-09-26 14:53:38',
            ),
            16 => 
            array (
                'id' => 17,
                'attachable_id' => 3,
                'attachable_type' => 'company',
                'attachmenttype_id' => 9,
                'path' => 'uploads/2018/09/EfS33ezguAz63JZOkGa6Mwmicdz8eeziLLnAR7EO.pdf',
                'description' => 'Articles of association',
                'filename' => '5b83e44e955acsi-2.pdf',
                'authcode' => NULL,
                'envelope' => NULL,
                'document' => NULL,
                'status' => NULL,
                'created_by' => 9,
                'updated_by' => 9,
                'created_at' => '2018-09-26 14:53:49',
                'updated_at' => '2018-09-26 14:53:49',
            ),
        ));
        
        
    }
}