<?php

use Illuminate\Database\Seeder;

class CompaniesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('companies')->delete();
        
        \DB::table('companies')->insert(array (
            0 => 
            array (
                'id' => 1,
                'companyname' => 'Buyer & Supplier company',
                'address' => '10 wadi el nile',
                'district' => NULL,
                'city_id' => 3796,
                'country_id' => 229,
                'companytype_id' => 3,
                'supplierterm_id' => 2,
                'pobox' => '123456',
                'email' => 's_abdelnabi@metragroup.com',
                'phone' => '+11111111111111',
                'fax' => '+22222222222222',
                'license' => 'ABC-123',
                'tax' => '2',
                'vatno' => NULL,
                'vat' => 5.0,
                'incorporated' => '2018-09-01',
                'employees' => 11,
                'creditlimit' => 10000.0,
                'margin' => 0.0,
                'payment' => 0.0,
                'website' => 'bizzmo.com',
                'operating' => NULL,
                'accountname' => 'Buyer & Supplier company',
                'bankname' => 'asdasd',
                'accountnumber' => 'asdasd',
                'iban' => 'asdasd',
                'routingcode' => 'asdasd',
                'swift' => 'asdasd',
                'otp' => NULL,
                'sapnumber' => '0100005548',
                'sapvendornumber' => '0001000450',
                'signatorydesignation' => 'jgfhjgfjhg',
                'signatoryphone' => '+56876876',
                'signatoryemail' => 'both@example.com',
                'signatoryname' => 'Both name',
                'active' => 1,
                'confirmed' => 1,
                'sameowner' => 1,
                'basicinfo' => 1,
                'authsignatory' => 1,
                'shareholders' => 1,
                'beneficialowners' => 1,
                'directors' => 1,
                'business' => 1,
                'banks' => 1,
                'tenant_id' => 7,
                'vendor_signed' => 1,
                'customer_signed' => 1,
                'created_by' => 7,
                'updated_by' => 7,
                'created_at' => '2018-09-26 14:39:50',
                'updated_at' => '2019-07-11 08:08:33',
            ),
            1 => 
            array (
                'id' => 2,
                'companyname' => 'Buyer company',
                'address' => '20 wadi el nile',
                'district' => NULL,
                'city_id' => 3796,
                'country_id' => 229,
                'companytype_id' => 1,
                'supplierterm_id' => 6,
                'pobox' => '123456',
                'email' => 'sherifan@gmail.com',
            'phone' => '+(111) 111 1111 1111',
            'fax' => '+(222) 222 2222 2222',
                'license' => '123-GTF',
                'tax' => '2',
                'vatno' => NULL,
                'vat' => 5.0,
                'incorporated' => '2018-09-01',
                'employees' => 11,
                'creditlimit' => 10000.0,
                'margin' => 0.0,
                'payment' => 0.0,
                'website' => 'bizzmo.com',
                'operating' => NULL,
                'accountname' => NULL,
                'bankname' => NULL,
                'accountnumber' => NULL,
                'iban' => NULL,
                'routingcode' => NULL,
                'swift' => NULL,
                'otp' => NULL,
                'sapnumber' => '0100005549',
                'sapvendornumber' => NULL,
                'signatorydesignation' => NULL,
                'signatoryphone' => NULL,
                'signatoryemail' => 'sherifan@gmail.com',
                'signatoryname' => 'Cust name',
                'active' => 1,
                'confirmed' => 1,
                'sameowner' => 1,
                'basicinfo' => 1,
                'authsignatory' => 1,
                'shareholders' => 1,
                'beneficialowners' => 1,
                'directors' => 1,
                'business' => 1,
                'banks' => 1,
                'tenant_id' => 8,
                'vendor_signed' => 0,
                'customer_signed' => 1,
                'created_by' => 8,
                'updated_by' => 8,
                'created_at' => '2018-09-26 14:49:25',
                'updated_at' => '2019-08-27 13:04:17',
            ),
            2 => 
            array (
                'id' => 3,
                'companyname' => 'Supplier company',
                'address' => '30 wadi el nile',
                'district' => NULL,
                'city_id' => 3796,
                'country_id' => 229,
                'companytype_id' => 2,
                'supplierterm_id' => 4,
                'pobox' => '123456',
                'email' => 'sherif@egynile.com',
            'phone' => '+(111) 111 1111 1111',
            'fax' => '+(222) 222 2222 2222',
                'license' => '12122-13',
                'tax' => '2',
                'vatno' => NULL,
                'vat' => 5.0,
                'incorporated' => '2018-09-01',
                'employees' => 11,
                'creditlimit' => 0.0,
                'margin' => 0.0,
                'payment' => 0.0,
                'website' => 'bizzmo.com',
                'operating' => NULL,
                'accountname' => 'asdasd',
                'bankname' => 'asdasd',
                'accountnumber' => 'asdasd',
                'iban' => 'asdasd',
                'routingcode' => 'asdasd',
                'swift' => 'asdasd',
                'otp' => NULL,
                'sapnumber' => NULL,
                'sapvendornumber' => '0001000451',
                'signatorydesignation' => NULL,
                'signatoryphone' => NULL,
                'signatoryemail' => 'sherif@egynile.com',
                'signatoryname' => 'Vend name',
                'active' => 1,
                'confirmed' => 1,
                'sameowner' => 1,
                'basicinfo' => 1,
                'authsignatory' => 1,
                'shareholders' => 1,
                'beneficialowners' => 1,
                'directors' => 1,
                'business' => 1,
                'banks' => 1,
                'tenant_id' => 9,
                'vendor_signed' => 1,
                'customer_signed' => 0,
                'created_by' => 9,
                'updated_by' => 9,
                'created_at' => '2018-09-26 14:53:57',
                'updated_at' => '2019-06-19 12:31:58',
            ),
        ));
        
        
    }
}