<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('countries')->delete();
        
        \DB::table('countries')->insert(array (
            0 => 
            array (
                'id' => 1,
                'isocode' => 'AF',
                'countryname' => 'Afghanistan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'isocode' => 'AL',
                'countryname' => 'Albania',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'isocode' => 'DZ',
                'countryname' => 'Algeria',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'isocode' => 'AS',
                'countryname' => 'American Samoa',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'isocode' => 'AD',
                'countryname' => 'Andorra',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'isocode' => 'AO',
                'countryname' => 'Angola',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'isocode' => 'AI',
                'countryname' => 'Anguilla',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'isocode' => 'AQ',
                'countryname' => 'Antarctica',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'isocode' => 'AG',
                'countryname' => 'Antigua And Barbuda',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'isocode' => 'AR',
                'countryname' => 'Argentina',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'isocode' => 'AM',
                'countryname' => 'Armenia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'isocode' => 'AW',
                'countryname' => 'Aruba',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'isocode' => 'AU',
                'countryname' => 'Australia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'isocode' => 'AT',
                'countryname' => 'Austria',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'isocode' => 'AZ',
                'countryname' => 'Azerbaijan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'isocode' => 'BS',
                'countryname' => 'Bahamas The',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'isocode' => 'BH',
                'countryname' => 'Bahrain',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'isocode' => 'BD',
                'countryname' => 'Bangladesh',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'isocode' => 'BB',
                'countryname' => 'Barbados',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'isocode' => 'BY',
                'countryname' => 'Belarus',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'isocode' => 'BE',
                'countryname' => 'Belgium',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'isocode' => 'BZ',
                'countryname' => 'Belize',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'isocode' => 'BJ',
                'countryname' => 'Benin',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'isocode' => 'BM',
                'countryname' => 'Bermuda',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'isocode' => 'BT',
                'countryname' => 'Bhutan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'isocode' => 'BO',
                'countryname' => 'Bolivia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'isocode' => 'BA',
                'countryname' => 'Bosnia and Herzegovina',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'isocode' => 'BW',
                'countryname' => 'Botswana',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'isocode' => 'BV',
                'countryname' => 'Bouvet Island',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'isocode' => 'BR',
                'countryname' => 'Brazil',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'isocode' => 'IO',
                'countryname' => 'British Indian Ocean Territory',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'isocode' => 'BN',
                'countryname' => 'Brunei',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'isocode' => 'BG',
                'countryname' => 'Bulgaria',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'isocode' => 'BF',
                'countryname' => 'Burkina Faso',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            34 => 
            array (
                'id' => 35,
                'isocode' => 'BI',
                'countryname' => 'Burundi',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            35 => 
            array (
                'id' => 36,
                'isocode' => 'KH',
                'countryname' => 'Cambodia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'isocode' => 'CM',
                'countryname' => 'Cameroon',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'isocode' => 'CA',
                'countryname' => 'Canada',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'isocode' => 'CV',
                'countryname' => 'Cape Verde',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'isocode' => 'KY',
                'countryname' => 'Cayman Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'isocode' => 'CF',
                'countryname' => 'Central African Republic',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'isocode' => 'TD',
                'countryname' => 'Chad',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'isocode' => 'CL',
                'countryname' => 'Chile',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'isocode' => 'CN',
                'countryname' => 'China',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'isocode' => 'CX',
                'countryname' => 'Christmas Island',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            45 => 
            array (
                'id' => 46,
                'isocode' => 'CC',
            'countryname' => 'Cocos (Keeling) Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            46 => 
            array (
                'id' => 47,
                'isocode' => 'CO',
                'countryname' => 'Colombia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            47 => 
            array (
                'id' => 48,
                'isocode' => 'KM',
                'countryname' => 'Comoros',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            48 => 
            array (
                'id' => 49,
                'isocode' => 'CG',
                'countryname' => 'Congo',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            49 => 
            array (
                'id' => 50,
                'isocode' => 'CD',
                'countryname' => 'Congo The Democratic Republic Of The',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            50 => 
            array (
                'id' => 51,
                'isocode' => 'CK',
                'countryname' => 'Cook Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            51 => 
            array (
                'id' => 52,
                'isocode' => 'CR',
                'countryname' => 'Costa Rica',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            52 => 
            array (
                'id' => 53,
                'isocode' => 'CI',
            'countryname' => 'Cote D\'Ivoire (Ivory Coast)',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            53 => 
            array (
                'id' => 54,
                'isocode' => 'HR',
            'countryname' => 'Croatia (Hrvatska)',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            54 => 
            array (
                'id' => 55,
                'isocode' => 'CU',
                'countryname' => 'Cuba',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            55 => 
            array (
                'id' => 56,
                'isocode' => 'CY',
                'countryname' => 'Cyprus',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            56 => 
            array (
                'id' => 57,
                'isocode' => 'CZ',
                'countryname' => 'Czech Republic',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            57 => 
            array (
                'id' => 58,
                'isocode' => 'DK',
                'countryname' => 'Denmark',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            58 => 
            array (
                'id' => 59,
                'isocode' => 'DJ',
                'countryname' => 'Djibouti',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            59 => 
            array (
                'id' => 60,
                'isocode' => 'DM',
                'countryname' => 'Dominica',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            60 => 
            array (
                'id' => 61,
                'isocode' => 'DO',
                'countryname' => 'Dominican Republic',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            61 => 
            array (
                'id' => 62,
                'isocode' => 'TP',
                'countryname' => 'East Timor',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            62 => 
            array (
                'id' => 63,
                'isocode' => 'EC',
                'countryname' => 'Ecuador',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            63 => 
            array (
                'id' => 64,
                'isocode' => 'EG',
                'countryname' => 'Egypt',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            64 => 
            array (
                'id' => 65,
                'isocode' => 'SV',
                'countryname' => 'El Salvador',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            65 => 
            array (
                'id' => 66,
                'isocode' => 'GQ',
                'countryname' => 'Equatorial Guinea',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            66 => 
            array (
                'id' => 67,
                'isocode' => 'ER',
                'countryname' => 'Eritrea',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            67 => 
            array (
                'id' => 68,
                'isocode' => 'EE',
                'countryname' => 'Estonia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            68 => 
            array (
                'id' => 69,
                'isocode' => 'ET',
                'countryname' => 'Ethiopia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            69 => 
            array (
                'id' => 70,
                'isocode' => 'XA',
                'countryname' => 'External Territories of Australia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            70 => 
            array (
                'id' => 71,
                'isocode' => 'FK',
                'countryname' => 'Falkland Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            71 => 
            array (
                'id' => 72,
                'isocode' => 'FO',
                'countryname' => 'Faroe Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            72 => 
            array (
                'id' => 73,
                'isocode' => 'FJ',
                'countryname' => 'Fiji Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            73 => 
            array (
                'id' => 74,
                'isocode' => 'FI',
                'countryname' => 'Finland',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            74 => 
            array (
                'id' => 75,
                'isocode' => 'FR',
                'countryname' => 'France',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            75 => 
            array (
                'id' => 76,
                'isocode' => 'GF',
                'countryname' => 'French Guiana',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            76 => 
            array (
                'id' => 77,
                'isocode' => 'PF',
                'countryname' => 'French Polynesia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            77 => 
            array (
                'id' => 78,
                'isocode' => 'TF',
                'countryname' => 'French Southern Territories',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            78 => 
            array (
                'id' => 79,
                'isocode' => 'GA',
                'countryname' => 'Gabon',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            79 => 
            array (
                'id' => 80,
                'isocode' => 'GM',
                'countryname' => 'Gambia The',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            80 => 
            array (
                'id' => 81,
                'isocode' => 'GE',
                'countryname' => 'Georgia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            81 => 
            array (
                'id' => 82,
                'isocode' => 'DE',
                'countryname' => 'Germany',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            82 => 
            array (
                'id' => 83,
                'isocode' => 'GH',
                'countryname' => 'Ghana',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            83 => 
            array (
                'id' => 84,
                'isocode' => 'GI',
                'countryname' => 'Gibraltar',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            84 => 
            array (
                'id' => 85,
                'isocode' => 'GR',
                'countryname' => 'Greece',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            85 => 
            array (
                'id' => 86,
                'isocode' => 'GL',
                'countryname' => 'Greenland',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            86 => 
            array (
                'id' => 87,
                'isocode' => 'GD',
                'countryname' => 'Grenada',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            87 => 
            array (
                'id' => 88,
                'isocode' => 'GP',
                'countryname' => 'Guadeloupe',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            88 => 
            array (
                'id' => 89,
                'isocode' => 'GU',
                'countryname' => 'Guam',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            89 => 
            array (
                'id' => 90,
                'isocode' => 'GT',
                'countryname' => 'Guatemala',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            90 => 
            array (
                'id' => 91,
                'isocode' => 'XU',
                'countryname' => 'Guernsey and Alderney',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            91 => 
            array (
                'id' => 92,
                'isocode' => 'GN',
                'countryname' => 'Guinea',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            92 => 
            array (
                'id' => 93,
                'isocode' => 'GW',
                'countryname' => 'Guinea-Bissau',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            93 => 
            array (
                'id' => 94,
                'isocode' => 'GY',
                'countryname' => 'Guyana',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            94 => 
            array (
                'id' => 95,
                'isocode' => 'HT',
                'countryname' => 'Haiti',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            95 => 
            array (
                'id' => 96,
                'isocode' => 'HM',
                'countryname' => 'Heard and McDonald Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            96 => 
            array (
                'id' => 97,
                'isocode' => 'HN',
                'countryname' => 'Honduras',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            97 => 
            array (
                'id' => 98,
                'isocode' => 'HK',
                'countryname' => 'Hong Kong S.A.R.',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            98 => 
            array (
                'id' => 99,
                'isocode' => 'HU',
                'countryname' => 'Hungary',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            99 => 
            array (
                'id' => 100,
                'isocode' => 'IS',
                'countryname' => 'Iceland',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            100 => 
            array (
                'id' => 101,
                'isocode' => 'IN',
                'countryname' => 'India',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            101 => 
            array (
                'id' => 102,
                'isocode' => 'ID',
                'countryname' => 'Indonesia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            102 => 
            array (
                'id' => 104,
                'isocode' => 'IQ',
                'countryname' => 'Iraq',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            103 => 
            array (
                'id' => 105,
                'isocode' => 'IE',
                'countryname' => 'Ireland',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            104 => 
            array (
                'id' => 106,
                'isocode' => 'IL',
                'countryname' => 'Israel',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            105 => 
            array (
                'id' => 107,
                'isocode' => 'IT',
                'countryname' => 'Italy',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            106 => 
            array (
                'id' => 108,
                'isocode' => 'JM',
                'countryname' => 'Jamaica',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            107 => 
            array (
                'id' => 109,
                'isocode' => 'JP',
                'countryname' => 'Japan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            108 => 
            array (
                'id' => 110,
                'isocode' => 'XJ',
                'countryname' => 'Jersey',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            109 => 
            array (
                'id' => 111,
                'isocode' => 'JO',
                'countryname' => 'Jordan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            110 => 
            array (
                'id' => 112,
                'isocode' => 'KZ',
                'countryname' => 'Kazakhstan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            111 => 
            array (
                'id' => 113,
                'isocode' => 'KE',
                'countryname' => 'Kenya',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            112 => 
            array (
                'id' => 114,
                'isocode' => 'KI',
                'countryname' => 'Kiribati',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            113 => 
            array (
                'id' => 116,
                'isocode' => 'KR',
                'countryname' => 'Korea South',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            114 => 
            array (
                'id' => 117,
                'isocode' => 'KW',
                'countryname' => 'Kuwait',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            115 => 
            array (
                'id' => 118,
                'isocode' => 'KG',
                'countryname' => 'Kyrgyzstan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            116 => 
            array (
                'id' => 119,
                'isocode' => 'LA',
                'countryname' => 'Laos',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            117 => 
            array (
                'id' => 120,
                'isocode' => 'LV',
                'countryname' => 'Latvia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            118 => 
            array (
                'id' => 121,
                'isocode' => 'LB',
                'countryname' => 'Lebanon',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            119 => 
            array (
                'id' => 122,
                'isocode' => 'LS',
                'countryname' => 'Lesotho',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            120 => 
            array (
                'id' => 123,
                'isocode' => 'LR',
                'countryname' => 'Liberia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            121 => 
            array (
                'id' => 124,
                'isocode' => 'LY',
                'countryname' => 'Libya',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            122 => 
            array (
                'id' => 125,
                'isocode' => 'LI',
                'countryname' => 'Liechtenstein',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            123 => 
            array (
                'id' => 126,
                'isocode' => 'LT',
                'countryname' => 'Lithuania',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            124 => 
            array (
                'id' => 127,
                'isocode' => 'LU',
                'countryname' => 'Luxembourg',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            125 => 
            array (
                'id' => 128,
                'isocode' => 'MO',
                'countryname' => 'Macau S.A.R.',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            126 => 
            array (
                'id' => 129,
                'isocode' => 'MK',
                'countryname' => 'Macedonia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            127 => 
            array (
                'id' => 130,
                'isocode' => 'MG',
                'countryname' => 'Madagascar',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            128 => 
            array (
                'id' => 131,
                'isocode' => 'MW',
                'countryname' => 'Malawi',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            129 => 
            array (
                'id' => 132,
                'isocode' => 'MY',
                'countryname' => 'Malaysia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            130 => 
            array (
                'id' => 133,
                'isocode' => 'MV',
                'countryname' => 'Maldives',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            131 => 
            array (
                'id' => 134,
                'isocode' => 'ML',
                'countryname' => 'Mali',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            132 => 
            array (
                'id' => 135,
                'isocode' => 'MT',
                'countryname' => 'Malta',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            133 => 
            array (
                'id' => 136,
                'isocode' => 'XM',
            'countryname' => 'Man (Isle of)',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            134 => 
            array (
                'id' => 137,
                'isocode' => 'MH',
                'countryname' => 'Marshall Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            135 => 
            array (
                'id' => 138,
                'isocode' => 'MQ',
                'countryname' => 'Martinique',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            136 => 
            array (
                'id' => 139,
                'isocode' => 'MR',
                'countryname' => 'Mauritania',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            137 => 
            array (
                'id' => 140,
                'isocode' => 'MU',
                'countryname' => 'Mauritius',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            138 => 
            array (
                'id' => 141,
                'isocode' => 'YT',
                'countryname' => 'Mayotte',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            139 => 
            array (
                'id' => 142,
                'isocode' => 'MX',
                'countryname' => 'Mexico',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            140 => 
            array (
                'id' => 143,
                'isocode' => 'FM',
                'countryname' => 'Micronesia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            141 => 
            array (
                'id' => 144,
                'isocode' => 'MD',
                'countryname' => 'Moldova',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            142 => 
            array (
                'id' => 145,
                'isocode' => 'MC',
                'countryname' => 'Monaco',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            143 => 
            array (
                'id' => 146,
                'isocode' => 'MN',
                'countryname' => 'Mongolia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            144 => 
            array (
                'id' => 147,
                'isocode' => 'MS',
                'countryname' => 'Montserrat',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            145 => 
            array (
                'id' => 148,
                'isocode' => 'MA',
                'countryname' => 'Morocco',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            146 => 
            array (
                'id' => 149,
                'isocode' => 'MZ',
                'countryname' => 'Mozambique',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            147 => 
            array (
                'id' => 150,
                'isocode' => 'MM',
                'countryname' => 'Myanmar',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            148 => 
            array (
                'id' => 151,
                'isocode' => 'NA',
                'countryname' => 'Namibia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            149 => 
            array (
                'id' => 152,
                'isocode' => 'NR',
                'countryname' => 'Nauru',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            150 => 
            array (
                'id' => 153,
                'isocode' => 'NP',
                'countryname' => 'Nepal',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            151 => 
            array (
                'id' => 154,
                'isocode' => 'AN',
                'countryname' => 'Netherlands Antilles',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            152 => 
            array (
                'id' => 155,
                'isocode' => 'NL',
                'countryname' => 'Netherlands The',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            153 => 
            array (
                'id' => 156,
                'isocode' => 'NC',
                'countryname' => 'New Caledonia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            154 => 
            array (
                'id' => 157,
                'isocode' => 'NZ',
                'countryname' => 'New Zealand',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            155 => 
            array (
                'id' => 158,
                'isocode' => 'NI',
                'countryname' => 'Nicaragua',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            156 => 
            array (
                'id' => 159,
                'isocode' => 'NE',
                'countryname' => 'Niger',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            157 => 
            array (
                'id' => 160,
                'isocode' => 'NG',
                'countryname' => 'Nigeria',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            158 => 
            array (
                'id' => 161,
                'isocode' => 'NU',
                'countryname' => 'Niue',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            159 => 
            array (
                'id' => 162,
                'isocode' => 'NF',
                'countryname' => 'Norfolk Island',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            160 => 
            array (
                'id' => 163,
                'isocode' => 'MP',
                'countryname' => 'Northern Mariana Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            161 => 
            array (
                'id' => 164,
                'isocode' => 'NO',
                'countryname' => 'Norway',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            162 => 
            array (
                'id' => 165,
                'isocode' => 'OM',
                'countryname' => 'Oman',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            163 => 
            array (
                'id' => 166,
                'isocode' => 'PK',
                'countryname' => 'Pakistan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            164 => 
            array (
                'id' => 167,
                'isocode' => 'PW',
                'countryname' => 'Palau',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            165 => 
            array (
                'id' => 168,
                'isocode' => 'PS',
                'countryname' => 'Palestinian Territory Occupied',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            166 => 
            array (
                'id' => 169,
                'isocode' => 'PA',
                'countryname' => 'Panama',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            167 => 
            array (
                'id' => 170,
                'isocode' => 'PG',
                'countryname' => 'Papua new Guinea',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            168 => 
            array (
                'id' => 171,
                'isocode' => 'PY',
                'countryname' => 'Paraguay',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            169 => 
            array (
                'id' => 172,
                'isocode' => 'PE',
                'countryname' => 'Peru',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            170 => 
            array (
                'id' => 173,
                'isocode' => 'PH',
                'countryname' => 'Philippines',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            171 => 
            array (
                'id' => 174,
                'isocode' => 'PN',
                'countryname' => 'Pitcairn Island',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            172 => 
            array (
                'id' => 175,
                'isocode' => 'PL',
                'countryname' => 'Poland',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            173 => 
            array (
                'id' => 176,
                'isocode' => 'PT',
                'countryname' => 'Portugal',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            174 => 
            array (
                'id' => 177,
                'isocode' => 'PR',
                'countryname' => 'Puerto Rico',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            175 => 
            array (
                'id' => 178,
                'isocode' => 'QA',
                'countryname' => 'Qatar',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            176 => 
            array (
                'id' => 179,
                'isocode' => 'RE',
                'countryname' => 'Reunion',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            177 => 
            array (
                'id' => 180,
                'isocode' => 'RO',
                'countryname' => 'Romania',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            178 => 
            array (
                'id' => 181,
                'isocode' => 'RU',
                'countryname' => 'Russia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            179 => 
            array (
                'id' => 182,
                'isocode' => 'RW',
                'countryname' => 'Rwanda',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            180 => 
            array (
                'id' => 183,
                'isocode' => 'SH',
                'countryname' => 'Saint Helena',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            181 => 
            array (
                'id' => 184,
                'isocode' => 'KN',
                'countryname' => 'Saint Kitts And Nevis',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            182 => 
            array (
                'id' => 185,
                'isocode' => 'LC',
                'countryname' => 'Saint Lucia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            183 => 
            array (
                'id' => 186,
                'isocode' => 'PM',
                'countryname' => 'Saint Pierre and Miquelon',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            184 => 
            array (
                'id' => 187,
                'isocode' => 'VC',
                'countryname' => 'Saint Vincent And The Grenadines',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            185 => 
            array (
                'id' => 188,
                'isocode' => 'WS',
                'countryname' => 'Samoa',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            186 => 
            array (
                'id' => 189,
                'isocode' => 'SM',
                'countryname' => 'San Marino',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            187 => 
            array (
                'id' => 190,
                'isocode' => 'ST',
                'countryname' => 'Sao Tome and Principe',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            188 => 
            array (
                'id' => 191,
                'isocode' => 'SA',
                'countryname' => 'Saudi Arabia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 1,
            ),
            189 => 
            array (
                'id' => 192,
                'isocode' => 'SN',
                'countryname' => 'Senegal',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            190 => 
            array (
                'id' => 193,
                'isocode' => 'RS',
                'countryname' => 'Serbia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            191 => 
            array (
                'id' => 194,
                'isocode' => 'SC',
                'countryname' => 'Seychelles',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            192 => 
            array (
                'id' => 195,
                'isocode' => 'SL',
                'countryname' => 'Sierra Leone',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            193 => 
            array (
                'id' => 196,
                'isocode' => 'SG',
                'countryname' => 'Singapore',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            194 => 
            array (
                'id' => 197,
                'isocode' => 'SK',
                'countryname' => 'Slovakia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            195 => 
            array (
                'id' => 198,
                'isocode' => 'SI',
                'countryname' => 'Slovenia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            196 => 
            array (
                'id' => 199,
                'isocode' => 'XG',
                'countryname' => 'Smaller Territories of the UK',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            197 => 
            array (
                'id' => 200,
                'isocode' => 'SB',
                'countryname' => 'Solomon Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            198 => 
            array (
                'id' => 201,
                'isocode' => 'SO',
                'countryname' => 'Somalia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            199 => 
            array (
                'id' => 202,
                'isocode' => 'ZA',
                'countryname' => 'South Africa',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            200 => 
            array (
                'id' => 203,
                'isocode' => 'GS',
                'countryname' => 'South Georgia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            201 => 
            array (
                'id' => 204,
                'isocode' => 'SS',
                'countryname' => 'South Sudan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            202 => 
            array (
                'id' => 205,
                'isocode' => 'ES',
                'countryname' => 'Spain',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            203 => 
            array (
                'id' => 206,
                'isocode' => 'LK',
                'countryname' => 'Sri Lanka',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            204 => 
            array (
                'id' => 208,
                'isocode' => 'SR',
                'countryname' => 'Suriname',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            205 => 
            array (
                'id' => 209,
                'isocode' => 'SJ',
                'countryname' => 'Svalbard And Jan Mayen Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            206 => 
            array (
                'id' => 210,
                'isocode' => 'SZ',
                'countryname' => 'Swaziland',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            207 => 
            array (
                'id' => 211,
                'isocode' => 'SE',
                'countryname' => 'Sweden',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            208 => 
            array (
                'id' => 212,
                'isocode' => 'CH',
                'countryname' => 'Switzerland',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            209 => 
            array (
                'id' => 214,
                'isocode' => 'TW',
                'countryname' => 'Taiwan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            210 => 
            array (
                'id' => 215,
                'isocode' => 'TJ',
                'countryname' => 'Tajikistan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            211 => 
            array (
                'id' => 216,
                'isocode' => 'TZ',
                'countryname' => 'Tanzania',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            212 => 
            array (
                'id' => 217,
                'isocode' => 'TH',
                'countryname' => 'Thailand',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            213 => 
            array (
                'id' => 218,
                'isocode' => 'TG',
                'countryname' => 'Togo',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            214 => 
            array (
                'id' => 219,
                'isocode' => 'TK',
                'countryname' => 'Tokelau',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            215 => 
            array (
                'id' => 220,
                'isocode' => 'TO',
                'countryname' => 'Tonga',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            216 => 
            array (
                'id' => 221,
                'isocode' => 'TT',
                'countryname' => 'Trinidad And Tobago',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            217 => 
            array (
                'id' => 222,
                'isocode' => 'TN',
                'countryname' => 'Tunisia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            218 => 
            array (
                'id' => 223,
                'isocode' => 'TR',
                'countryname' => 'Turkey',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            219 => 
            array (
                'id' => 224,
                'isocode' => 'TM',
                'countryname' => 'Turkmenistan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            220 => 
            array (
                'id' => 225,
                'isocode' => 'TC',
                'countryname' => 'Turks And Caicos Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            221 => 
            array (
                'id' => 226,
                'isocode' => 'TV',
                'countryname' => 'Tuvalu',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            222 => 
            array (
                'id' => 227,
                'isocode' => 'UG',
                'countryname' => 'Uganda',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            223 => 
            array (
                'id' => 228,
                'isocode' => 'UA',
                'countryname' => 'Ukraine',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            224 => 
            array (
                'id' => 229,
                'isocode' => 'AE',
                'countryname' => 'United Arab Emirates',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 1,
            ),
            225 => 
            array (
                'id' => 230,
                'isocode' => 'GB',
                'countryname' => 'United Kingdom',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            226 => 
            array (
                'id' => 231,
                'isocode' => 'US',
                'countryname' => 'United States',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            227 => 
            array (
                'id' => 232,
                'isocode' => 'UM',
                'countryname' => 'United States Minor Outlying Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            228 => 
            array (
                'id' => 233,
                'isocode' => 'UY',
                'countryname' => 'Uruguay',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            229 => 
            array (
                'id' => 234,
                'isocode' => 'UZ',
                'countryname' => 'Uzbekistan',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            230 => 
            array (
                'id' => 235,
                'isocode' => 'VU',
                'countryname' => 'Vanuatu',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            231 => 
            array (
                'id' => 236,
                'isocode' => 'VA',
            'countryname' => 'Vatican City State (Holy See)',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            232 => 
            array (
                'id' => 237,
                'isocode' => 'VE',
                'countryname' => 'Venezuela',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            233 => 
            array (
                'id' => 238,
                'isocode' => 'VN',
                'countryname' => 'Vietnam',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            234 => 
            array (
                'id' => 239,
                'isocode' => 'VG',
            'countryname' => 'Virgin Islands (British)',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            235 => 
            array (
                'id' => 240,
                'isocode' => 'VI',
            'countryname' => 'Virgin Islands (US)',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            236 => 
            array (
                'id' => 241,
                'isocode' => 'WF',
                'countryname' => 'Wallis And Futuna Islands',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            237 => 
            array (
                'id' => 242,
                'isocode' => 'EH',
                'countryname' => 'Western Sahara',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            238 => 
            array (
                'id' => 243,
                'isocode' => 'YE',
                'countryname' => 'Yemen',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            239 => 
            array (
                'id' => 244,
                'isocode' => 'YU',
                'countryname' => 'Yugoslavia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            240 => 
            array (
                'id' => 245,
                'isocode' => 'ZM',
                'countryname' => 'Zambia',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
            241 => 
            array (
                'id' => 246,
                'isocode' => 'ZW',
                'countryname' => 'Zimbabwe',
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-10-01 00:00:00',
                'updated_at' => '2017-10-01 00:00:00',
                'allowed' => 0,
            ),
        ));
        
        
    }
}